-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'DAILY_REPORT_SUBMITTED';
ALTER TYPE "NotificationType" ADD VALUE 'DAILY_REPORT_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE 'DAILY_REPORT_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE 'WORK_ORDER_STATUS_CHANGED';
