-- AlterTable
ALTER TABLE "Quotation" ADD COLUMN "createdById" TEXT;

-- AddForeignKey
ALTER TABLE "Quotation" ADD CONSTRAINT "Quotation_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'QUOTATION_ACCEPTED';
ALTER TYPE "NotificationType" ADD VALUE 'QUOTATION_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE 'INTERVENTION_REPORT_SUBMITTED';
ALTER TYPE "NotificationType" ADD VALUE 'INTERVENTION_REPORT_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE 'INTERVENTION_REPORT_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE 'MAINTENANCE_REQUEST_SCHEDULED';
ALTER TYPE "NotificationType" ADD VALUE 'MAINTENANCE_REQUEST_CANCELLED';
ALTER TYPE "NotificationType" ADD VALUE 'MAINTENANCE_REQUEST_COMPLETED';
ALTER TYPE "NotificationType" ADD VALUE 'MAINTENANCE_REPORT_SUBMITTED';
ALTER TYPE "NotificationType" ADD VALUE 'MAINTENANCE_REPORT_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE 'MAINTENANCE_REPORT_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE 'PROJECT_ASSIGNED';
